# Site settings
title: LemonStand Community Projects
email: community@lemonstand.com
description: > # 
  These are some of our community projects, including themes, libraries,
  and design resources.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: lemonstand
github_username:  lemonstand

# Build settings
markdown: kramdown
